eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
exception:
  printStackTrace: true

signing:
  key: "cGVyc29uYWwgZmluYW5jZSBzZXJ2aWNl"

# For detailed logging during development
logging:
  level:
    org:
      com: ERROR
      springframework: ERROR
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: ERROR
